name: Testsidecho
favicon: null
layout_spectrum: 0.8187490694690496
typography_spectrum: 0.15805358532816172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8764424088876694
  lightness: 0.15438720118254423
  saturation: 0.5893647545017302
  rhythmicContrast: 0.12156740739010274
purpose: []
