name: Testsidecho
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5eaee'
    - '#ffffff'
    - '#0f806c'
    - '#1d6387'
    - '#86a8cd'
  brandStrength: 0.8764424088876694
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
